version: '3.7'

services:
  
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3
    environment:
     - SERVICES=iam
     - DEFAULT_REGION=eu-west-2
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "4593:4593"
     - "9999:8080"
    volumes:
      - localstack-data:/tmp/localstack

volumes:

  localstack-data:
    name: localstack-data