// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface PageNodeModel {
    Title:                     string;
    Menu:                      Menu;
    Breadcrumb:                Breadcrumb;
    QuestionBlockList:         QuestionBlockList[];
    TypeCode:                  string;
    RecordIdentifier:          RecordIdentifier;
    IsContinueButtonVisible:   boolean;
    IsCancelTreeButtonVisible: boolean;
    IsBackViewable:            boolean;
    IsEndingTreeNode:          boolean;
    SectionTreeGuid:           string;
}

export interface Breadcrumb {
}

export interface Menu {
    SectionTreeGuid:   string;
    IsShowMenu:        boolean;
    CurrentMenuText:   null;
    MenuModelItemList: any[];
}

export interface QuestionBlockList {
    QuestionBlockTypeCode: string;
    LanguageList:          LanguageList[];
    CollectorList:         CollectorList[];
    IsLastBlockOnPage:     boolean;
    SortOrder:             number;
    Title:                 string;
    IsSummary:             boolean;
    SummaryItemList:       SummaryItemList[] | null;
    SummaryItemHeaderDict: { [key: string]: SummaryItemHeaderDict } | null;
}

export interface CollectorList {
    Id:                            number;
    Label:                         string;
    LabelCssClass:                 null;
    DefaultValue:                  string;
    MaxWidth:                      number;
    MaxCharacters:                 number;
    Rows:                          number;
    OptionList:                    OptionList[];
    DataDictionaryId:              number | null;
    FormInputTypeCode:             string;
    LookupTable:                   null | string;
    CustomCollectorDotNETFunction: null;
    IsNewLine:                     boolean;
    SortOrder:                     number;
    CssStyleOptions:               null;
    CssClass:                      null;
    OptionalHtmlAttributes:        null;
    ValidationRuleList:            ValidationRuleList[];
    IsRequired:                    boolean;
    JQuerySelector:                null;
    JQueryCode:                    string;
    ObjectNumber:                  null;
    CollectorTypeCd:               string;
    Pager:                         Pager | null;
    HtmlIdentifier:                string;
    HtmlName:                      string;
}

export interface OptionList {
    Value:       string;
    Description: string;
    SortOrder:   number;
    IsSelected:  null;
}

export interface Pager {
    TotalItems:  number;
    CurrentPage: number;
    PageSize:    number;
    TotalPages:  number;
    StartPage:   number;
    EndPage:     number;
}

export interface ValidationRuleList {
    Regex:    string;
    Message:  string;
    TypeCode: string;
}

export interface LanguageList {
    Type:      number;
    Language:  string;
    SortOrder: number;
}

export interface SummaryItemHeaderDict {
    LabelText:            string;
    ColumnNumber:         number;
    Colspan:              null;
    CssClass:             null;
    IsCssAppliedToColumn: boolean;
}

export interface SummaryItemList {
    ObjectNumber:          number;
    ObjectTypeCd:          null;
    Column1:               string;
    Column2:               string;
    Column3:               string;
    Column4:               string;
    Column5:               string;
    Column6:               string;
    SummaryItemActionList: any[];
    CollectorModelList:    any[];
}

export interface RecordIdentifier {
    QpcIdNum:                           string;
    BatchId:                            number;
    RiskStateCd:                        string;
    CarrierId:                          number;
    ProgramId:                          number;
    RuleGroupId:                        number;
    ExceptionGroupId:                   number;
    ApplicationTypeCd:                  string;
    CustomizationGroupMembershipArray:  number[];
    CustomizationGroupMembershipString: string;
    ParentObjectNumber:                 null;
    ObjectNumber:                       null;
}
